"""Add game_user Association Table

Revision ID: 70a84def7cb3
Revises: 2358f2d14bbc
Create Date: 2023-07-14 13:56:04.851623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70a84def7cb3'
down_revision = '2358f2d14bbc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
